// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/ppdai/framework/raptor/proto/helloworld.proto
package com.ppdai.framework.raptor.proto;

import com.ppdai.framework.raptor.annotation.RaptorField;
import com.ppdai.framework.raptor.annotation.RaptorMessage;

@RaptorMessage(
    version = "version.0.1",
    protoFile = "helloworld"
)
public final class Cat {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_COLOR = "";

  @RaptorField(
      fieldType = "string",
      order = 1,
      name = "color"
  )
  private String color;

  public Cat() {
  }

  public Cat(String color) {
    this.color = color;
  }

  public String getColor() {
    return this.color;
  }

  public void setColor(String color) {
    this.color=color;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (color != null) builder.append(", color=").append(color);
    return builder.replace(0, 2, "Cat{").append('}').toString();
  }
}
