// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/ppdai/framework/raptor/proto/helloworld.proto
package com.ppdai.framework.raptor.proto;

import com.ppdai.framework.raptor.annotation.RaptorField;
import com.ppdai.framework.raptor.annotation.RaptorMessage;

import java.util.Objects;

@RaptorMessage(
    version = "version.0.1",
    protoFile = "helloworld"
)
public final class Cat {
  private static final long serialVersionUID = 0L;

  @RaptorField(
      fieldType = "string",
      order = 1,
      name = "color"
  )
  private String color;

  public Cat() {
  }

  public Cat(String color) {
    this.color = color;
  }

  public String getColor() {
    return this.color;
  }

  public void setColor(String color) {
    this.color=color;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Cat)) return false;
    Cat o = (Cat) other;
    return true
        && Objects.equals(color, o.color);
  }

  @Override
  public int hashCode() {
    int result = 0;
    result = result * 37 + (color != null ? color.hashCode() : 0);
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (color != null) builder.append(", color=").append(color);
    return builder.replace(0, 2, "Cat{").append('}').toString();
  }
}
