// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/ppdai/framework/raptor/proto/helloworld.proto
package com.ppdai.framework.raptor.proto;

import com.ppdai.framework.raptor.annotation.RaptorInterface;
import com.ppdai.framework.raptor.annotation.RaptorMethod;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@RaptorInterface(
    appId = "appId",
    appName = "demo",
    version = "version.0.1",
    protoFile = "helloworld",
    library = "spring"
)
@RequestMapping(
    path = "/more"
)
public interface MoreService {
  @RequestMapping(
      method = RequestMethod.GET
  )
  @RaptorMethod
  HelloReply testGet1(HelloRequest request);

  @RequestMapping(
      path = "/get2",
      method = RequestMethod.GET
  )
  @RaptorMethod
  HelloReply testGet2(HelloRequest request);

  @RequestMapping(
      path = "/post1",
      method = RequestMethod.POST
  )
  @RaptorMethod
  HelloReply testPost1(HelloRequest request);

  @RequestMapping(
      path = "/put1",
      method = RequestMethod.PUT
  )
  @RaptorMethod
  HelloReply testPut1(HelloRequest request);

  @RequestMapping(
      path = "/delete",
      method = RequestMethod.DELETE
  )
  @RaptorMethod
  HelloReply testDelete1(HelloRequest request);
}
