// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/ppdai/framework/raptor/proto/helloworld.proto
package com.ppdai.framework.raptor.proto;

import com.ppdai.framework.raptor.annotation.RaptorInterface;
import com.ppdai.framework.raptor.annotation.RaptorMethod;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@RaptorInterface(
    appId = "appId",
    appName = "demo",
    version = "version.0.1",
    protoFile = "helloworld",
    library = "spring"
)
@RequestMapping(
    path = "/more"
)
public interface MoreService {
  @RequestMapping(
      path = "/get1",
      method = RequestMethod.GET
  )
  @RaptorMethod
  HelloReply testGet1(HelloRequest request, @RequestParam("p1") String p1);

  @RequestMapping(
      path = "/get2/{p1}",
      method = RequestMethod.GET
  )
  @RaptorMethod
  HelloReply testGet2(HelloRequest request, @PathVariable("p1") String p1);

  @RequestMapping(
      path = "/post1",
      method = RequestMethod.POST
  )
  @RaptorMethod
  HelloReply testPost1(HelloRequest request, @RequestParam("p1") String p1);

  @RequestMapping(
      path = "/post2/{p1}/{p2}",
      method = RequestMethod.POST
  )
  @RaptorMethod
  HelloReply testPost2(HelloRequest request, @RequestParam("p3") String p3,
                       @PathVariable("p1") String p1, @PathVariable("p2") int p2);

  @RequestMapping(
      path = "/put1",
      method = RequestMethod.PUT
  )
  @RaptorMethod
  HelloReply testPut1(HelloRequest request, @RequestParam("p1") String p1);

  @RequestMapping(
      path = "/delete/{p2}",
      method = RequestMethod.DELETE
  )
  @RaptorMethod
  HelloReply testDelete1(HelloRequest request, @PathVariable("p2") int p2);
}
