// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: com/ppdai/framework/raptor/proto/helloworld.proto
package com.ppdai.framework.raptor.proto;

import com.ppdai.framework.raptor.annotation.RaptorInterface;
import com.ppdai.framework.raptor.annotation.RaptorMethod;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@RaptorInterface(
    appId = "123456",
    appName = "demo",
    version = "version.0.1",
    protoFile = "helloworld",
    library = "spring"
)
@RequestMapping
public interface Simple {
  @RequestMapping(
      path = "/raptor/com.ppdai.framework.raptor.proto.Simple/sayHello",
      method = RequestMethod.POST
  )
  @RaptorMethod
  HelloReply sayHello(HelloRequest request);
}
